-- MySQL Script generated by MySQL Workbench
-- Sun Oct 23 14:44:28 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jksndb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jksndb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jksndb` DEFAULT CHARACTER SET utf8 ;
USE `jksndb` ;

-- -----------------------------------------------------
-- Table `jksndb`.`equip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jksndb`.`equip` ;

CREATE TABLE IF NOT EXISTS `jksndb`.`equip` (
  `equipid` INT NOT NULL,
  `model` VARCHAR(45) NULL,
  `gpssensor_sensorid` INT NOT NULL,
  PRIMARY KEY (`equipid`, `gpssensor_sensorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jksndb`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jksndb`.`contract` ;

CREATE TABLE IF NOT EXISTS `jksndb`.`contract` (
  `contractid` INT NOT NULL,
  `signtime` DATETIME NULL,
  `starttime` DATETIME NULL,
  `endtime` DATETIME NULL,
  `duration` INT NULL,
  `income` INT NULL,
  PRIMARY KEY (`contractid`),
  CONSTRAINT `companyid`
    FOREIGN KEY ()
    REFERENCES `jksndb`.`customer` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipid`
    FOREIGN KEY ()
    REFERENCES `jksndb`.`equip` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jksndb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jksndb`.`customer` ;

CREATE TABLE IF NOT EXISTS `jksndb`.`customer` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `cellphone` VARCHAR(45) NULL,
  `companyname` VARCHAR(45) NULL,
  `companyid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`companyid`),
  CONSTRAINT `contractid`
    FOREIGN KEY ()
    REFERENCES `jksndb`.`contract` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `jksndb`.`gpssensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jksndb`.`gpssensor` ;

CREATE TABLE IF NOT EXISTS `jksndb`.`gpssensor` (
  `sensorid` INT NOT NULL,
  `isequiped` TINYINT(1) NULL,
  `status` TINYINT(1) NULL,
  `batterypercent` INT NULL,
  `model` VARCHAR(45) NULL,
  `equip_equipid` INT NOT NULL,
  `equip_gpssensor_sensorid` INT NOT NULL,
  PRIMARY KEY (`sensorid`, `equip_equipid`, `equip_gpssensor_sensorid`),
  CONSTRAINT `equipid`
    FOREIGN KEY ()
    REFERENCES `jksndb`.`equip` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jksndb`.`gpsdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jksndb`.`gpsdata` ;

CREATE TABLE IF NOT EXISTS `jksndb`.`gpsdata` (
  `gpsdataid` INT NOT NULL,
  `time` DATETIME NULL,
  `longitude` FLOAT NULL,
  `latitude` VARCHAR(45) NULL,
  PRIMARY KEY (`gpsdataid`),
  CONSTRAINT `gpssensorid`
    FOREIGN KEY ()
    REFERENCES `jksndb`.`gpssensor` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO user1;
 DROP USER user1;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
