# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Categoty Description', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(default='The Serial Number', max_length=128)),
                ('model', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(default='Describe this equip', max_length=1024)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='jokoson.Category')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='Gpsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gpssensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('model', models.CharField(max_length=64)),
                ('batterypercent', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpssensors', to='jokoson.Category')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpssensors', to='jokoson.Equip')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(auto_now_add=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('money', models.FloatField()),
                ('valid', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='jokoson.Equip')),
            ],
            options={
                'ordering': ('signtime',),
            },
        ),
        migrations.CreateModel(
            name='OrderHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist', to='jokoson.Equip')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist', to='jokoson.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('cell_phone', models.CharField(max_length=64)),
                ('office_phone', models.CharField(blank=True, max_length=64)),
                ('address1', models.CharField(max_length=64)),
                ('address2', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='gpssensor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpssensors', to='jokoson.Vendor'),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpsdatas', to='jokoson.Gpssensor'),
        ),
        migrations.AddField(
            model_name='equip',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='jokoson.Vendor'),
        ),
    ]
