# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='', max_length=1024)),
                ('status', models.IntegerField()),
                ('health', models.CharField(max_length=64)),
                ('gps_status', models.IntegerField(blank=True, null=True)),
                ('gps_model', models.CharField(blank=True, max_length=64, null=True)),
                ('gps_batterypercent', models.IntegerField(blank=True, null=True)),
                ('gps_time', models.DateTimeField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('city', models.CharField(max_length=64)),
                ('cell_phone', models.CharField(blank=True, max_length=64)),
                ('office_phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='', max_length=1024)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='db.Manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signtime', models.DateTimeField(auto_now_add=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('total_cost', models.FloatField()),
                ('valid', models.BooleanField(default=True)),
                ('equip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='db.Equip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('signtime',),
            },
        ),
        migrations.AddField(
            model_name='equip',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='db.Manufacture'),
        ),
        migrations.AddField(
            model_name='equip',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='db.Model'),
        ),
    ]
